manifest_version = 1

[module]
name = "Thermometer"
id = "thermometer"
description = "A set of commands dedicated to providing information about things."
version = "1.0.2"
license = "GNU GPLv3"
authors = ["Fripe"]
requirements = [
    "aiohttp"
]
